spring:
  application:
    name: dmitriy-shmatkov-test-task
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/banking-db;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
server:
  error:
    include-message: always
