spring:
  application:
    name: dmitriy-shmatkov-test-task
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:banking-db
  jpa:
    hibernate:
      ddl-auto: validate
server:
  error:
    include-message: always