INSERT INTO ACCOUNT(BALANCE)
VALUES (100),
       (200),
       (300);

INSERT INTO TRANSACTION(TYPE, TIMESTAMP, ACCOUNT_NUMBER, AMOUNT)
VALUES ('CREATE', LOCALTIMESTAMP(3), 1, 100),
       ('CREATE', LOCALTIMESTAMP(3), 2, 200),
       ('CREATE', LOCALTIMESTAMP(3), 3, 300);
