DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS TRANSACTION CASCADE;

CREATE TABLE ACCOUNT
(
    ACCOUNT_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
    BALANCE        BIGINT NOT NULL CHECK (balance >= 0)
);

CREATE TABLE TRANSACTION
(
    TRANSACTION_ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE                     VARCHAR(31)  NOT NULL,
    TIMESTAMP                TIMESTAMP(3) NOT NULL,
    ACCOUNT_NUMBER           BIGINT       NOT NULL REFERENCES ACCOUNT (ACCOUNT_NUMBER),
    AMOUNT                   BIGINT       NOT NULL,
    RECIPIENT_ACCOUNT_NUMBER BIGINT REFERENCES ACCOUNT (ACCOUNT_NUMBER)
);
